artifacts_root: artifacts

dataingestion:
   root_dir: artifacts/data_ingestion
   source_URL: https://github.com/entbappy/Branching-tutorial/raw/refs/heads/master/samsumdata.zip
   local_data_file: artifacts/data_ingestion/samsumdata.zip
   unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]

